[package]
name = "CodinGame-AI"
version = "0.1.0"
authors = ["Tatsuya Katsushima"]
edition = "2018"

[dependencies]
chrono = "0.4.26"
itertools = "0.11.0"
libc = "0.2.147"
rand = "0.8.5"
regex = "1.8.4"
time = "0.3.22"

[profile.release]
lto = true
panic = 'abort'
debug = true
