[package]
name = "CodinGame-AI"
version = "0.1.0"
authors = ["Tatsuya Katsushima"]
edition = "2018"

[dependencies]
chrono = "0.4.19"
itertools = "0.10.0"
libc = "0.2.93"
rand = "0.8.3"
regex = "1.4.5"
time = "0.2.26"

[profile.release]
lto = true
panic = 'abort'
debug = true
